.TH hev\-tristripCube 1 "January 2010"

.SH NAME
hev-savgCube
.SH SYNOPSIS
.B hev-savgCube 

.SH DESCRIPTION 
.I hev-savgCube 
creates a cube centered on the origin with radius 1
and writes its data in savg file format to 
.I stdout.

The cube is drawn as a single tristrip.

.SH SEE ALSO
savg, savg-cube

.SH AUTHORS
.PP
John Kelso
.TP
.br
January 2010
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/




