#!gmake

PUBLIC_BINS = hev-animator

PRIVATE_BINS = tim

MAN_PAGES = *.1

include $(HEV_IDEA_DIR)/gnumakefile.include

# add in the name of the cxx file used by your main program
hev-animator.d: hev-animatorGUI.cxx


