.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-lightEditor 1 "September 2012" 
.SH NAME
.B
hev-lightEditor
- Interactive lighting control

.SH SYNOPSIS
.B "hev-lightEditor" 
[ options ]

.SH DESCRIPTION
.PP
.B
hev-lightEditor 
provides interactive control of lighting.


.SH EXAMPLE

hev-lightEditor > $IRIS_CONTROL_FIFO

.SH OPTIONS

-e   Echo all communications with IRIS

-h   Display help message.

.SH NOTES
A more complete explanation of 
.B
hev-lightEditor
can be found at 

 file:///usr/local/HEV/idea/src/hev-lightEditor/doc/hev-lightEditor.html

or at the corresponding location in /usr/local/HEV-beta.


.\" .SH SEE ALSO




