#include <iris.h>

// this file is generated by the makefile from the fluid file
#include "hev-collabGUI.cxx"

////////////////////////////////////////////////////////////////////////
int main(int argc, char **argv)
{
    
    // send dtkMsg files to stderr
    // to get INFO level messages set the envvar DTK_SPEW=info
    dtkMsg.setFile(stderr) ;

    // set the signls that kill us off
    iris::Signal(cleanup) ;
    
    ////////////////
    // this stuff is for command parsing- it pulls out the fltk arguments
    // and leaves the rest for our program
    if(dtkFLTKOptions_get(argc, (const char **) argv,
			    &fltk_argc,  &fltk_argv,
			    &other_argc, &other_argv)) 
    {
	usage() ;
	return 1 ;
    }
    
    // parse the local arguments and do other setup
    if(! init(other_argc, other_argv))
    {
	usage() ;
	return 1 ;
    }
    
    ////////////////
    // create the main window
    main_window = make_window() ;
    // KLUDGE ALERT! chop off the object mover button if --move wasn't specified
    if (moverNodeName.size() == 0) main_window->size(165,115) ;
    main_window->end();
    main_window->show(fltk_argc, fltk_argv);

    // disable killing the window using the close button or escape button
    if (noEscape) main_window->callback(doNothingCB);

    loadWands() ;

    // the GUI loop
    float secs = float(ticks)/1000000.f ;
    while (running)
    {
	process() ;
	Fl::wait(secs) ;
    };

    ////////////////
    // here's your chance to do cleanup
    dtkMsg.add(DTKMSG_DEBUG, "hev-collab: after GUI has exited\n") ;

    return 0 ;
}


