#!gmake

############# define MACROS #########################################

# define PROJECT to be the directory name containing this software.  If not
# defined, it defaults to name of this directory.
PROJECT = hev-brokenWindow

# these are the file(s) that have the man page(s). Installed in $HEV_SAVG_DIR/man/*
MAN_PAGES = hev-brokenWindow.1

# these are the binaries that get compiled AND installed as public binaries
# in $HEV_SAVG_DIR/bin/*
PUBLIC_BINS = 

# these are the binaries that get compiled AND installed as private binaries
# in $HEV_SAVG_DIR/etc/$(PROJECT)/bin/*
PRIVATE_BINS =

# these are DSOs that get compiled AND installed as public DSOs
# in $HEV_SAVG_DIR/lib/*
PUBLIC_DSOS = 

# these are the DSOs that get compiled AND installed as private DSOs
# in $HEV_SAVG_DIR/etc/$(PROJECT)/lib/*
PRIVATE_DSOS =

# same thing for scripts that get installed
# Public into $HEV_SAVG_DIR/scripts/*
PUBLIC_SCRIPTS = hev-brokenWindow

# Private into $HEV_SAVG_DIR/etc/$(PROJECT)/scripts/*
PRIVATE_SCRIPTS = 

# these are data files used by the project, and others too
# in $HEV_SAVG_DIR/data
PUBLIC_DATA = input.txt

# these are data files used by the project, private,
# in $HEV_SAVG_DIR/etc/$(PROJECT)/data
PRIVATE_DATA = 

################## makefile.include ##################################
# define CXX, CFLAGS, LIBS, etc.

# creates phoney target build

# creates real target test, and targets for PUBLIC_DSOS, PRIVATE_DSOS,
# PUBLIC_BINS, PRIVATE_BINS, install, clean, cleaner, distclean

# add or modify or make dependencies to them as needed after the include
# statement

include $(HEV_IDEA_DIR)/gnumakefile.include

