#!/usr/bin/env python

import sys
import vtk
from optparse import OptionParser

def showHelp():
    sys.stderr.write('\nUsage:\nhev-vtkAddNormals [options] inFName outFName\n')
    sys.exit(1)

use = "Usage: %prog [options] inFName outFName"

# PARSE COMMAND LINE
parser = OptionParser(usage = use)

# ASSIGN VALUES
parser.add_option("--fangle", "--fa", dest="fangle", type="float", default="30")
parser.add_option("--auto", "-a", dest="auto", action="store_false", default=True)
parser.add_option("--flip", "-f", dest="flip", action="store_true", default=False)

options, args = parser.parse_args()


#SET INPUT AND OUTPUT FILE
inputdatafile = args[0]
outputdatafile = args[1]

#READER
reader = vtk.vtkPolyDataReader()
reader.SetFileName(inputdatafile)

#PROCESS
pdn = vtk.vtkPolyDataNormals()
pdn.SetInputConnection(reader.GetOutputPort())
pdn.SplittingOn()
pdn.ConsistencyOn()
pdn.ComputePointNormalsOn()
pdn.ComputeCellNormalsOn()
pdn.NonManifoldTraversalOn()
pdn.SetFeatureAngle(options.fangle)

if options.auto == True:
    pdn.AutoOrientNormalsOn()
else:
    pdn.AutoOrientNormalsOff()

if options.flip == False:
    pdn.FlipNormalsOff()
else:
    pdn.FlipNormalsOn()

#FILEWRITER
write = vtk.vtkGenericDataObjectWriter()
write.SetFileTypeToASCII()
write.SetInput(pdn.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
