#!/usr/bin/env python

import sys
import vtk

def showHelp():
    sys.stderr.write('\nUsage:\nhev-vtkReverse [-CellOnly(-c) || -NormalOnly(-n)] inFName outFName\n')
    sys.exit(1)


#reading command line and assigning values
if len(sys.argv) == 4:
    outputdatafile = sys.argv[-1]
    inputdatafile = sys.argv[-2]
    option = sys.argv[-3]

else:
    if len(sys.argv) != 3:
        showHelp()
    outputdatafile = sys.argv[-1]
    inputdatafile = sys.argv[-2]
    option = "none"

#data reader set up and fed with inputdata
reader = vtk.vtkGenericDataObjectReader()
reader.SetFileName(inputdatafile)

#reversesense set up and executed
reverse = vtk.vtkReverseSense()
reverse.SetInputConnection(reader.GetOutputPort())
if option == "none":
    reverse.ReverseCellsOn()
    reverse.ReverseNormalsOn()
elif option.lower() == "-cellonly" or option.lower() == "-c":
    reverse.ReverseCellsOn()
    reverse.ReverseNormalsOff()
elif option.lower() == "-normalonly" or option.lower() == "-n":
    reverse.ReverseCellsOff()
    reverse.ReverseNormalsOn()
else:
    print "the optional argument can either be '-CellOnly' (short: '-c') or '-NormalOnly' (short: '-n')"
    showHelp()

#filewriter set up and executed
writef = vtk.vtkGenericDataObjectWriter()
writef.SetFileTypeToASCII()
writef.SetInput(reverse.GetOutput())
writef.SetFileName(outputdatafile)
writef.Write()
writef.Update()
