#!/usr/bin/env python

import sys
import vtk
from optparse import OptionParser

def showHelp():
    sys.stderr.write('\nUsage:\nhev-vtkGaussianSmooth [options] inFName outFName\n')
    sys.exit(1)

use = "Usage: %prog [options] inFName outFName"

# PARSE COMMAND LINE
parser = OptionParser(usage = use)

# ASSIGN VALUES
parser.add_option("--stddev", "--sd", dest="dev", nargs=3, type="float", default=(2,2,2))
parser.add_option("--rfactor", "--r", dest="rad", nargs=3, type="float", default=(1.5,1.5,1.5))
parser.add_option("--dimensionality", "--d", dest="dim", type="int", default="3")

options, args = parser.parse_args()

#CHECK
if len(args) != 2:
    print "Specify inFileName & outFileName as arguments."
    showHelp()

#SET INPUT AND OUTPUT FILE
inputdatafile = args[-2]
outputdatafile = args[-1]

#READER
reader = vtk.vtkStructuredPointsReader()
reader.SetFileName(inputdatafile)

#PROCESS
gauss = vtk.vtkImageGaussianSmooth()
gauss.SetInput(reader.GetOutput())
gauss.SetDimensionality(options.dim)
gauss.SetStandardDeviations(options.dev)
gauss.SetRadiusFactors(options.rad)


#FILEWRITER
write = vtk.vtkStructuredPointsWriter()
write.SetFileTypeToASCII()
write.SetInput(gauss.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
