#!/usr/bin/env python

import sys
import vtk
from optparse import OptionParser

def showHelp():
    sys.stderr.write('\nUsage:\nhev-vtkVectorGlyph [options] inFName outFName\n')
    sys.exit(1)

use = "Usage: %prog [options] inFName outFName"

# PARSE COMMAND LINE
parser = OptionParser(usage = use)

# ASSIGN VALUES
parser.add_option("--scalefactor", "--sf", dest="scale", type="float", default="1")
parser.add_option("--useNormals", "-n", dest="normals", action="store_true", default=False)

options, args = parser.parse_args()

#SET INPUT AND OUTPUT FILE

if len(args) != 2:
    showHelp()

inputdatafile = args[-2]
outputdatafile = args[-1]

#DATAREADER
read = vtk.vtkGenericDataObjectReader()
read.SetFileName(inputdatafile)

#PROCESS
hedge = vtk.vtkHedgeHog()
hedge.SetInput(read.GetOutput())
hedge.SetScaleFactor(options.scale)
if options.normals:
    hedge.SetVectorModeToUseNormal()

#FILEWRITER
write = vtk.vtkPolyDataWriter()
write.SetFileTypeToASCII()
write.SetInput(hedge.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
