#!/usr/bin/env python

import sys
import vtk
from optparse import OptionParser

def showHelp():
    sys.stderr.write('\nUsage:\nhev-CleanPolyData [options] inFName outFName\n')
    sys.exit(1)

use = "Usage: %prog [options] inFName outFName"

# PARSE COMMAND LINE
parser = OptionParser(usage = use)

# ASSIGN VALUES
parser.add_option("--pointTolerance", "--p", dest="tolerance", type="float", default="0.0")

options, args = parser.parse_args()

#SET INPUT AND OUTPUT FILE
if len(args) == 2:
    inputdatafile = args[-2]
    outputdatafile = args[-1]
else:
    showHelp()

#READER
reader = vtk.vtkPolyDataReader()
reader.SetFileName(inputdatafile)

#PROCESS
clean = vtk.vtkCleanPolyData()
clean.SetInput(reader.GetOutput())
clean.SetAbsoluteTolerance(options.tolerance)
clean.ToleranceIsAbsoluteOn()
clean.ConvertLinesToPointsOn()
clean.ConvertPolysToLinesOn()
clean.ConvertStripsToPolysOn()
clean.PointMergingOn()

#FILEWRITER
write = vtk.vtkPolyDataWriter()
write.SetInput(clean.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
