#!/usr/bin/env python

import sys
import vtk

def showHelp():
    sys.stderr.write('\nUsage:\nhev-vtkVectorMagnitude inFName outFName\n')
    sys.exit(1)

#SET INPUT AND OUTPUT FILE

if len(sys.argv) != 3:
    showHelp()

inputdatafile = sys.argv[-2]
outputdatafile = sys.argv[-1]

#DATAREADER
read = vtk.vtkGenericDataObjectReader()
read.SetFileName(inputdatafile)

#PROCESS
mag = vtk.vtkVectorNorm()
mag.SetInputConnection(read.GetOutputPort())

#FILEWRITER
write = vtk.vtkGenericDataObjectWriter()
write.SetFileTypeToASCII()
write.SetInput(mag.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
