#!/usr/bin/env python

import sys
import vtk
from optparse import OptionParser

def showHelp():
    sys.stderr.write('\nUsage:\nhev-GridToGeom [options] inFName outFName\n')
    sys.exit(1)

use = "Usage: %prog [options] inFName outFName"

# PARSE COMMAND LINE
parser = OptionParser(usage = use)

# ASSIGN VALUES
parser.add_option("--noNormals", "-n", dest="normals", action="store_true", default=False)

options, args = parser.parse_args()

#SET INPUT AND OUTPUT FILE
inputdatafile = args[-2]
outputdatafile = args[-1]

#DATAREADER
reader = vtk.vtkGenericDataObjectReader()
reader.SetFileName(inputdatafile)

#Geometry Filter
geomf = vtk.vtkGeometryFilter()
geomf.SetInputConnection(reader.GetOutputPort())

#Avoid PolyDataNormals if -noNormals was set
if options.normals:
    obj = geomf

else:
    #Poly Data Normals
    obj = vtk.vtkPolyDataNormals()
    obj.SetInputConnection(geomf.GetOutputPort())
    obj.SetFeatureAngle(0)
    obj.ComputeCellNormalsOn()

#FILEWRITER
write = vtk.vtkGenericDataObjectWriter()
write.SetFileTypeToASCII()
write.SetInput(obj.GetOutput())
write.SetFileName(outputdatafile)
write.Write()
write.Update()
