#! /bin/sh

# Do a comparision test for a figure using a plane .savg file
# compared to the figure drawn with ivline and ivstick

# When display at teh same time only one figure should be visible

# steve@nist.gov
# March 18, 2008

export PATH=..:$PATH


p1="0 0 0"
p2="1 1 1"
p3="2 1 1"
p4="2 1 2"
p5="1 1 2"


(echo lines
 echo $p1
 echo $p2
 echo lines
 echo $p2
 echo $p3
 echo lines
 echo $p3
 echo $p4
 echo lines
 echo $p4
 echo $p5
 echo lines
 echo $p5
 echo $p2
 echo lines
 echo $p4
 echo $p2) > t1.savg

(ivline $p1 $p2
 ivline $p2 $p3
 ivline $p3 $p4
 ivline $p4 $p5
 ivline $p5 $p2
 ivline $p4 $p2) > t2.ivu

(ivstick $p1 $p2
 ivstick $p2 $p3
 ivstick $p3 $p4
 ivstick $p4 $p5
 ivstick $p5 $p2
 ivstick $p4 $p2) > t3.ivu

echo compare t1.savg t2.ivu t3.ivu


# test horizontal as a special case
ivstick $p5 $p4 > a2b.ivu
ivstick $p4 $p5 > b2a.ivu

echo compare a2b.ivu b2a.ivu


# Test radius parameter
(ivstick  SIDES  0 0  0   10 0 0 
 ivstick         0 0 -5   10 0 -5 .5
 ivstick  SIDES 10 0  5    0 0  5 .5) > tr.ivu

echo view tr.ivu
