# Bare bones GNUmakefile
# This directory is a bit outside the normal HEV framework,
# so its not clear if the usual HEV GNUmakefile works here.
# -sgs


build:
	echo in hev-testGenerateImages
	echo ; \
	echo ; \
	echo "# --------------------------------" ; \
	echo ; \
	echo hev-testGenerateImages ; \



install: build
	@if [ ! -d  ${HEVROOT}/test/renderTest/bin ] ; then mkdir ${HEVROOT}/test/renderTest/bin ; fi
	cp hev-testGenerateImages ${HEVROOT}/test/renderTest/bin


clean:

distclean:

