.TH HEV-VERSION 1 "December 2014" "NIST/ACMD" "HPCVG HEV"

.SH NAME
hev-version
- Print the current HEV version to standard output

.SH SYNOPSIS
.B hev-version
.I [-V]

.SH DESCRIPTION
.B hev-version
prints the current HEV version to standard output.
.TP
.I -V
print the date and user who tagged the current version.

.SH AUTHOR
Wesley Griffin, wesley.griffin@nist.gov

