#!/usr/bin/perl

if ($#ARGV != 1) {
    print STDERR "Usage: $0 <segments> <pitch>\n\n";
    print STDERR "Generate spiral test sphere made from line primitives\n\n";
    print STDERR "Sphere will have <segments> line segments\n";
    print STDERR "Spiral will wrap <pitch> times around sphere\n\n";
    print STDERR "Example: $0 512 16 > spiral.savg\n";
    exit 1;
}

my $pi=2*atan2(1,0);
my $vstep = $pi/$ARGV[0];
my $ustep = 2*$vstep*$ARGV[1];

for($u0=-$pi, $u1=$u0+$ustep, $v0=-$pi/2, $v1=$v0+$vstep;
    $v1<$pi/2;
    $u0=$u1, $u1+=$ustep, $v0=$v1, $v1+=$vstep)
  {
    my $x0 = sin($u0)*cos($v0), $y0=cos($u0)*cos($v0), $z0=sin($v0);
    my $x1 = sin($u1)*cos($v1), $y1=cos($u1)*cos($v1), $z1=sin($v1);
    print "line\n";
    print "$x0 $y0 $z0 ", .5+.5*$x0," ",.5+.5*$y0," ",.5+.5*$z0," 1\n";
    print "$x1 $y1 $z1 ", .5+.5*$x1," ",.5+.5*$y1," ",.5+.5*$z1," 1\n";
  }
