.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-raveSafety 1 "May, 2011" "NIST/ACMD/HPCVG" "HEV"

.SH NAME

hev-raveSafety - display a RAVE Room Safety Announcement on the front RAVE screen

.SH SYNOPSIS

\fBhev-raveSafetfy [file.png]\fR 

.SH DESCRIPTION

\fBhev-raveSafety\fR is a convenience utility to quickly display the
RAVE Room Safey Announcement on the front RAVE screen.


.SH FILES
.PP
The actual announcement is an PNG image created by Judy Terrill.
It can be accessed directly at
.IP
\fB$HEV_IDEA_DIR/etc/hev-raveSafety/data/raveSafety.png\fR

.PP
An optional \fB.png\fR may be sopefifed to be used instead.


.SH AUTHOR

.PP
Steve Satterfield, steve@nist.gov
