#! /bin/sh

# ivline - create a line segment between two specified points

# steve@nist.gov
# November 1, 2006

case $# in
6)
cat <<EOF
#Inventor V2.0 ascii
Separator {
Coordinate3 {
point [
EOF
echo $1 $2 $3 ","
echo $4 $5 $6
cat <<EOF
]
}
LineSet {
startIndex 0
numVertices 2
}
}
EOF
	;;
*)
	echo "Usage: ivline x1 y1 z1   x2 y2 z2"
	exit
	;;
esac
