#! /bin/sh

case $# in
0)
    r=1;
    ;;
1)
    r=$1;
    ;;
*)
    echo "Usage: ivsphere [radius]"
    echo "   default is 1"
    exit
    ;;
esac


echo "#Inventor V2.0 ascii"
echo "Separator {"
echo "Sphere { radius" $r "}"
echo "}"

