#! /bin/sh

# ivwirecube - create a unit wire frame cube Inventor file
#
# Usage:  ivwirecube x y
#
#  x y is the width and height of the "wires" 

case $# in
0)
   i=.01
   j=.01
   ;;
2)
   i=$1
   j=$2
   ;;
*)
   echo "Usage: ivwirecube [x y]"
   echo
   echo '   x y is the width and height of the "wires"'
   echo "   that make up the unit cube"
   echo
   echo "  example: ivwirecube .01 .01"
   echo 
   exit
   ;;
esac

d=.5

# x menbers
ivcube 1 $j $i | ivtranslate 0 -$d -$d
ivcube 1 $j $i | ivtranslate 0  $d -$d
ivcube 1 $j $i | ivtranslate 0 -$d  $d
ivcube 1 $j $i | ivtranslate 0  $d  $d

# y members
ivcube $i 1 $j | ivtranslate  $d 0  $d
ivcube $i 1 $j | ivtranslate -$d 0  $d
ivcube $i 1 $j | ivtranslate  $d 0 -$d
ivcube $i 1 $j | ivtranslate -$d 0 -$d

# z members
ivcube $i $j 1 | ivtranslate  $d  $d 0
ivcube $i $j 1 | ivtranslate -$d  $d 0
ivcube $i $j 1 | ivtranslate -$d -$d 0
ivcube $i $j 1 | ivtranslate  $d -$d 0

