.TH hev-newDemo 1 "October 2011"

.SH NAME

hev-newDemo \fIdirectory\fR

.SH SYNOPSIS

creates the directories and files needed for a new demo

.SH DESCRIPTION

\fBhev-newDemo\fR creates a new \fIdirectory\fR in the current directory and
populates it with the directories and files required for a new demo.

.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST Scientific Applications & Visualization Group
.br
June 2007
.br
\fBhttp://www.nist.gov/mcsd/savg/\fR

