.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-which 1 "June 2017" "NIST/ACMD/HPCVG" "HEV"

.SH NAME

hev-demoRunner

.SH SYNOPSIS

\fBhev-demoRunner [path]\fR 

.SH DESCRIPTION

\fIhev-demoRunner\fR is an experiment at a GIU for executing a sub-set of the installed demos. This is a convenient wrapper for \fIdtk-demoRunner\fR.

\fBTHIS IS A WORK IN PROGRESS\fR

.SH OPTIONS
.TP
path  is a path to a directory with a wrapper script for each demo.
The default is \fI/usr/local/demos/.demoRunner\fR.
Refer to this directory for example of how to create a custom demoRunner directory.

.SH AUTHOR

.PP
Steve Satterfield, steve@nist.gov

