#! /bin/bash

# hev-animatorMCP
# steve@nist.gov

#version="20120416"
#version="20121022"
version="20130109"

function usage {
cat > /dev/tty <<EOF

  Usage: hev-animatorMCP [-h] files ...  > Animation.mcp

    Convenience command to create a .mcp file on stdout suitable for
    adding an Animation button to the irisfly master control panel.


  Version: $version
EOF
exit 1
}

#
# Body of the script starts here
#

case $# in
0)
        usage
	;;
*)
	case $1 in
	-h*|--h*)
		usage
                ;;
	esac
	;;
esac



if [ $# == 0 ]
then
      usage
fi

# Must have at least one file
if [ $# == 0 ]
then
      usage
fi

FILES=""

for f in $*
do
   FILES="$FILES $f"

done

cat <<EOF
SIZE 85 20
BUTTON Animate
FIRST EXEC hev-animator --noescape frame $FILES  > \$IRIS_CONTROL_FIFO
ON EXEC hev-showWindow hev-animator
OFF EXEC hev-hideWindow hev-animator
EOF


# End of script
