.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-animationToTimeline 1 "November, 2011" "NIST/MCSD" "MCSD HEV"
.SH NAME
hev-animationToTimeline
- generate a timeline file to animate the display of child nodes of sequence and group
nodes

.SH SYNOPSIS
.B "hev-animationToTimeline"
.I [ --first n ] [ --last n ] [ --time t ] [ --descend ] file ... 

.SH PARAMETERS

.IP "--first \fIn\fR"
specifies the first frame number to use.  If omitted, 0 is used.

.IP "--last \fIn\fR"
specifies the last frame number to use.  If omitted, it defaults to the
number of child nodes minus 1.  If both --last and files are supplied, last
is checked to be sure it is less than the number of child nodes.

.IP "--time \fIt\fR"
specifies the amount of time to display each frame, in seconds.  This number
is the inverse of he frame rate. If omitted it defaults to .1, or 10 frames
per second.

.IP "--descend"
if supplied, specifies that if the top node of the file has only a single
child node, then nodes should be descended until a child node is reached
with more than one child node.  This is useful if the file has a top-level
transformation applied to it via iris-DCS.

.IP file
is the name of one or more OSG readable files.  Each file should return a
node with one or more child nodes.  All of the returned nodes need to have
the same number of child nodes.  All child nodes need to have unique
non-blank node names.

.SH DESCRIPTION
.PP
.I hev-animationToTimeline
writes a timeline file to stdout that displays frames of a flipbook
animation. 

See hev-timeline(5) for a description of the timeline file.

To convert the timeline file to an iris file use the hev-timelineToIris(1) command.

To get multiple loops of a flipbook, just concatenate multiple copies of the
timeline file into a single file, or supply the timeline file multiple times
to hev-timelineToIris.

For best results the loaded files should have the nodemasks turned off for
all the child nodes, or all but the first child node. If all the nodemasks are all on
then all child nodes will be momentarily displayed until the commands
generated by hev-timelineToIris via hev-animationToTimeline can be processed.

.SH EXAMPLE

See animation1.sh and animation2.sh in $HEVROOT/idea/src/hev-timeline

.SH SEE ALSO

hev-animator, hev-timelineToIris, hev-timeline

.SH AUTHOR

John Kelso, kelso@nist.gov,  NIST/ITL/MCSD


