.TH hev-graphicalTimelineBuilder 1 "August, 2016" "NIST/ACMD" "HEV"
.SH NAME
hev-graphicalTimelineBuilder
- a GUI tool to interactively build and edit a timeline file.

.SH SYNOPSIS
.B "hev-graphicalTimelineBuilder"

.SH DESCRIPTION
.PP
.I hev-graphicalTimelineBuilder
GUI tool to interactively build and edit a timeline file.

See hev-timeline(5) for a description of the timeline file.

To convert the timeline file to an iris file use the hev-timelineToIris(1) command.

.SH SEE ALSO

hev-timelineToIris, hev-timeline

.SH AUTHOR

Vinay Sriram,
Wesley Griffin

