#! /usr/bin/perl
#
# hyv-vtk2savg - see usage message below
#
# steve@nist.gov
#

$version="20100618";


use Getopt::Long;
use File::Basename;  #http://perldoc.perl.org/File/Basename.html


#####################
#  Usage subroutine #
#####################


sub usage {

print STDERR <<EOF

Usage: hyv-vtk2savg [--parallel n] phaseNumber  dataDir | vtkFile

  Convert the *.vtk files for a specified phaseNumber to *.savg,
  i.e isosurface. The iso value is specified by the corresponding *.iso file.


  --parallel n  specifies how many concurrent processes to be used convert
                in parallel. On a 2 CPU machine, n of 2 is a good number.

  phaseNumber   is an integer used to identify the phase being processed.
                This command is invoked multiple times for each desired 
		phase.

  dataDir       is an existing directory containing the phase files.
                The resulting iso files are written to dataDir
		with names in the form of *.iso.

  vtkFile       when a vtk file is specified rather than a directory name,
                then the single specified is vtk file is converted to an savg
                isosurface file in the current directory.


Version: $version

EOF
;
exit(1)
}

# End of Usage subroutine




############################
# Process the command line #
############################

$debugFlag=0;
$parallel=1;

$err=GetOptions("debug"         => \$debugFlag,
           "parallel:i"    => \$parallel);

#$n=@ARGV;
#print STDERR "err= $err n= $n\n";

if ($err == 0) {usage();}



if (@ARGV == 2) {
    $phaseNumber = shift;
    $data = shift;
} else {
    usage();
}


if ($debugFlag) {
    print STDERR "\n";
    print STDERR "debugFlag= $debugFlag\n";
    print STDERR "parallel= $parallel\n";
    print STDERR "phaseNumber= $phaseNumber\n";
    print STDERR "data= $data\n";
}



# Is the input data a single file or directory of file?
if ( -d $data ) {
    #print STDERR "$data is a directory\n";
    processDirFiles();
    #print STDERR "All Done\n";
} else {
    #print STDERR "$data is a file\n";
    processSingleFile()

}


#########################
# Process a single file #
#########################

sub processSingleFile {
    print STDERR "Process a single vtk file: $data\n";
	
    ($basename, $dirname, $suffix) = fileparse($data, ('.vtk'));

    $a=rindex($basename,"_");
    if ($a<0) {
	print STDERR "Phase number must be part of the file name: $basename\n";
	usage();
    }
    #$phaseNumber=substr($basename,$a+1);
    if ($debugFlag) {
	print STDERR "phaseNumber $phaseNumber\n";
    }

    $savgName=$basename.".savg";
    $isoName=$basename.".iso";
    if ($debugFlag) {
	print STDERR "data= $data\n";
	print STDERR "basename= $basename\n";
	print STDERR "path= $path\n";
	printf(STDERR "suffix= '%s'\n",$suffix);
	print STDERR "savgName= $savgName\n";
	print STDERR "isoName= $isoName\n";
    }
    if ($suffix eq '') {die("'$data' is not a vtk file or directory\n");}


    # Get the iso value
    $isoValue=getIsoValue($isoName);

    $isoCmd ="hev-vtkIsoSavg --d .6 $isoValue $data > $savgName";
    if ($debugFlag) {
	print STDERR "isoCmd= $isoCmd\n";
    }
    system($isoCmd);
	

    # Ensure that a a valid savg is produced. When the no file is produced,
    # create a valid empty file.

    if ( ! -s $savgName) {
	if ($debugFlag) {
	    print STDERR "Creating valid empty file: $savgName\n";
	}

	open(SAVG,">$savgName") || die("Can not open file: $savgName\n");
	print SAVG "#Empty SAVG file\n";
	close(SAVG);
    }

	
}


# Subroutine to read the corresponding iso file for the iso value

sub getIsoValue {
    # Make these local
    local($isoNameTemp,$isoValueTemp);
    #Get the passed parameter
    $isoNameTemp=$_[0];
    open(ISO,"<$isoNameTemp") || die("Can not open file: $isoNameTemp\n");

    $isoValueTemp=<ISO>;
    # is it a valid number
    if ( ! ($isoValueTemp =~ /^([+-]?)(?=\d|\.\d)\d*(\.\d*)?([Ee]([+-]?\d+))?$/ ) ) {
	die("$isoNameTemp contains bad data\n");
    }

    chop($isoValueTemp);
    return($isoValueTemp);
}




####################################
# Process a directory of vtk files #
####################################

sub processDirFiles {
    print STDERR "Process a directory of vtk files: $data\n";

    chdir($data) || die("Can not chdir to: $data\n");

    ($debugFlag) ? ($debugOption="--debug") : ($debugOption="");

    $pcount=$parallel;
    
    $fileList="*_".$phaseNumber.".vtk";
    print STDERR "fileList= $fileList\n";
    while ($vtkFile = < $fileList > ) {

	$cmd="hyv-vtk2savg $debugOption $phaseNumber $vtkFile";
	if ($debugFlag) {
	    print STDERR "cmd= $cmd\n";
	}
	if ($pid = fork) {
	    # parent here
	    #print STDERR "Parent\n";
	    $pcount--;
	    if ($pcount == 0) {
		while (wait != -1) {
		    #print STDERR "waiting\n";
		}
		$pcount=$parallel;
	    }
	} else {
	    # child here
	    #print STDERR "Child: $cmd\n";
	    exec($cmd);
	    exit 0;
	}


    }

    while (wait != -1) {
	#print STDERR "waiting\n";
    }
}

