#!/bin/sh

if [ -z $HEVROOT ]; then
  echo HEV environment not defined
  exit 1
fi

NODE=$(which node 2>/dev/null)
if [ -z $NODE ]; then
  source $HEVROOT/external/node/profile
fi

irisfly $* demo.iris

