FUNC RgbaLut1D noName  inArr[1] outArr[4]
  VAL_TRANSFORM NONE
  COLOR_INTERP HSV
  LIGHTING EMIT_ONLY
  NORMALIZE true
  PRE_INTEGRATE false
  LOOKUP_INTERP LINEAR
  TABLE_TYPE UCHAR
  TABLE_LEN 256
  COMBINE_RGBA true
  RGBLUT
    10   1 2 3
    20   5 6 7
    200   15 16 17
  END_RGBLUT
  ALPHALUT
    10   4
    20   8
    200   18
  END_ALPHALUT
END_FUNC noName
