.TH hyd-BIMGtoOSG 3 "Aug 2015" "NIST/ITL/ACMD/HPCVG" "HEV"

.SH NAME
hyd-BIMGtoOSG - 
create OSG files from BIMG files

.SH DESCRIPTION

\fBhyd-BIMGtoOSG\fR
parses BIMG files and creates OSG geometry files.

.SH AUTHOR
Wesley Griffin, wesley.griffin@nist.gov

.SH SEE ALSO
.BR hyd-utilities (3),
.BR irisfly (1).

