#! /usr/bin/perl
sub usage() {
  print "usage: $ARGV[0] < transfer.ggr > transfer.lut\n";
  print "converts GIMP gradient to SAVG color lookup table\n";
  exit 1;
}

# ggr format described in gimp source devel-docs/ggr.txt
usage() if (<> !~ /^GIMP Gradient/);  # header
usage() if (<> !~ /^Name:/);	      # gradient name
usage() if (<> !~ /^\d+/);	      # number of gradient lines

while(<>) {
  ($p0,$p1,$p2,
   $r0,$g0,$b0,$a0,
   $r2,$g2,$b2,$a2,
   $blendFunc,$colorType) = split; # split line into individual numbers
  printf("%d %f %f %f %f\n", $p0*255+.5, $r0,$g0,$b0,$a0);
  printf("%d %f %f %f %f\n", $p1*255+.5,
	 ($r0+$r2)/2,($g0+$g2)/2,($b0+$b2)/2,($a0+$a2)/2);
  printf("%d %f %f %f %f\n", $p2*255+.5, $r2,$g2,$b2,$a2);
}
