FUNC RgbaLut1D DefaultRgbaLut1D
  VAL_TRANSFORM NONE
  COLOR_INTERP DIVERGING
  LIGHTING GRAD_OPAQUE
  NORMALIZE true
  PRE_INTEGRATE false
  LOOKUP_INTERP LINEAR
  TABLE_TYPE UCHAR
  TABLE_LEN 256
  COMBINE_RGBA true
  RGBLUT
    0   1 0 0
    1   0 0 1
  END_RGBLUT
  ALPHALUT
    0   0.05
    1   0.05
  END_ALPHALUT
END_FUNC DefaultRgbaLut1D
