.TH hev-readButtons 1 "April 2011"
.SH NAME

hev-readButtons

.SH SYNOPSIS

\fBhev-readButtons [-d] [-i] [-N] [-u t] shmName

.SH DESCRIPTION

\fBhev-readButtons\fR
reads the specified DTK shared memory. This command is similar to the
the \fBdtk-readButtons\fR with less options. The advantage of this command is that
the values printed to
.I stdout
are flushed making it usable with redirection to a pipe.
.PP
The specified shared memory must exist prior to executing the command.

.SH OPTIONS

.IP \fB-d\fR
Discard consecutive duplicate values

.IP \fB-i\fR
Print the initial value.

.IP \fB-N\fR
Print the first \fBN\fR values, then exit.  \fBN\fR must be a integer
greater thn zero. 

.IP \fB-u\ t\fR
specifies how many microseconds to sleep at the end of each loop.  If not specified,
iris::GetUsleep() is used.


.SH OUTPUT

Output to stdout when a button changes state is
its integer value followed by its binary representation.
If there are multiple buttons, all the integers are written
first, followed by all of the binary values.
Example:  
      '5 00001010', indicates left and right buttons are pressed.

.SH "SEE ALSO"
.BR dtk-readButtons "(no man page currently available)"

.SH AUTHOR

.PP
John Kelso <kelso@nist.gov>, Steve Satterfield <steve@nist.gov>
.br
\fBhttp://www.nist.gov/mcsd/hpcvg/\fR

