.TH state 1 " June 2007"

.SH NAME

 hev-lowerWindow name ...

 hev-raiseWindow name ...

.SH DESCRIPTION

\fI hev-lowerWindow\fR requsts that the window manager lower the window
\fIname\fR 

\fI hev-raiseWindow\fR requsts that the window manager raise the window
\fIname\fR 

Multiple window names can be specified on the command line.

0 is returned if any window can be found.  -1 is returned on error.

.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST Scientific Applications & Visualization Group
.br
June 2007
.br
\fBhttp://www.nist.gov/mcsd/idea/\fR

