.TH state 1 " June 2007"

.SH NAME

 hev-mapWindow name ...

 hev-unmapWindow name ...

.SH DESCRIPTION

\fI hev-mapWindow\fR requsts that the window manager map the window
\fIname\fR 

\fI hev-unmapWindow\fR requsts that the window manager unmap the window
\fIname\fR 

Multiple window names can be specified on the command line.

0 is returned if any window can be found.  -1 is returned on error.


.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST Scientific Applications & Visualization Group
.br
June 2007
.br
\fBhttp://www.nist.gov/mcsd/mcsd/\fR

