#!/bin/sh

###############################
# dosg-ants - a script to generate a list
# of commands the DOSG family of
# the "Army of Ants"  in $PATH. This
# calls one or more helper script(s) so
# the calling environment must be correctly
# set to find them, usually by modifying
# the PATH env var.

echo
${PRIVATE_BINS}/compc dosg- #"$SUBSTRING"
