#!/bin/sh

###############################
# hev-ants - a script to generate a list
# of commands in the HEV family of
# the "Army of Ants"  in $PATH. This
# calls one or more helper script(s) so
# the calling environment must be correctly
# set to find them, usually by modifying
# the PATH env var.
#
# $SUBSTRING is an exported var set in hev-findAnts
#Debug echo "hev-ants: Starting..."
echo
echo "HEV Tools: " $@
echo ---------
${PRIVATE_BINS}/compc hev- $@
echo