#!/bin/sh

###############################
# iris-ants - a script to generate a list
# of commands in the IRIS family of
# the "Army of Ants"  in $PATH. This
# calls one or more helper script(s) so
# the calling environment must be correctly
# set to find them, usually by modifying
# the PATH env var.
#
# $SUBSTRING is an exported var set in hev-findAnts

echo
echo "IRIS Tools: "$@
echo ---------
${PRIVATE_BINS}/compc iris $@
echo
