#!/bin/sh

###############################
# savg-ants - a script to generate a list
# of commands in the SAVG family of
# the "Army of Ants"  in $PATH. This
# calls one or more helper script(s) so
# the calling environment must be correctly
# set to find them, usually by modifying
# the PATH env var.

echo
echo "SAVG Tools: "$@
echo ----------
${PRIVATE_BINS}/compc savg $@
echo
