.TH NETX-OUTDEGREECENTRALITY 1 "24 July 2012"

.SH NAME

netx-outDegreeCentrality


.SH SYNOPSIS

.B netx-outDegreeCentrality
.I  inputFile

.SH GRAPH LIMITATIONS
\fBDirected:\fR Yes
.br
\fBUndirected:\fR No
.br
\fBSelf-Loops:\fR Yes
.br
\fBParallel Edges:\fR Yes
.br
\fBOther:\fR None
.br .br
.PP
.SH DESCRIPTION

\fBnetx-outDegreeCentrality\fR prints the out-degree centrality of each node in the directed graph. This function uses a software package called NetworkX that must be installed for the function to work.
.br .P
.br .P
.PP
Example Output:					
.br .P						
node1 0.43234522
.br .P
node2 0.52380952
.br .P
node3 0.16666666
.br .P
.br .P
.PP
Where the first value on the line is the node name and the second is the out-degree centrality of that node.
.br .P
.br .P
.PP
\fBinputFile\fR is a file in edge-list format that contains only text. It does not have any header information. The nodes can have any name, as long as each node has a unique name (i.e. you can't have two nodes both named "sam" in the same graph). Optionally, after listing the two nodes, various other edge attributes can be assigned. In this function, the first attribute is assumed to be the weight of the edge. No other attribute is used in this function. Below are two example input files. The first has no attributes, the second has one, weight.
.br .P
.PP
Example One:
.br .P
node1 node2 
.br .P
node3 node1
.br .P
node4 node5
.br .P
.br .P
.PP
Where there is an edge between the two nodes on the same line.
.br .P
.br .P
.PP
Example Two:
.br .P
node1 node2 4
.br .P
node3 node1 3.14
.br .P
node4 node5 2
.br .P
.br .P
.PP
Where there is an edge between the first two entries (nodes) on the same line and the third number is the weight of that edge.
.br .P
.br .P
.PP 
.SH AUTHOR

Zachary Keller

.PP
July 2012

.PP 
High Performance Computing & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/hpcvg/
