#!/usr/bin/env python3
#Arg 1: edge-list graph file
#Arg 2: 'u' for undirected, 'd' for directed
#Weight must be positive

import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
else:
    print("Error: wrong number of arguments.")
    sys.exit()

if(sys.argv[2]=='u'):
    G=nx.MultiGraph()
elif(sys.argv[2]=='d'):
    G=nx.MultiDiGraph()

lines = []
for edge in myFile:
    lines.append(tuple(edge.split()))

if(len(lines[0])==2):
    G.add_edges_from(lines)
    for key,value in nx.closeness_vitality(G).items():
        print("Node:", key, "Closeness Vitality:", value)
elif(len(lines[0])>=3):
    for item in lines:
        G.add_weighted_edges_from([(item[0],item[1],float(item[2]))])
    for key,value in nx.closeness_vitality(G,weight='weight').items():
        print("Node:", key, "Closeness Vitality:", value)
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

myFile.close()
