#!/usr/bin/env python3
#Arg 1: edge-list graph file
#Arg 2: 'u' for undirected, 'd' for directed
#Graph must be connected

import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
else:
    print("Error: wrong number of arguments.")
    sys.exit()

if(sys.argv[2]=='u'):
    G=nx.MultiGraph()
elif(sys.argv[2]=='d'):
    G=nx.MultiDiGraph()

lines = []
for edge in myFile:
    lines.append(tuple(edge.split()))

if(len(lines[0])==2):
    G.add_edges_from(lines)
elif(len(lines[0])!=2):
    for item in lines:
        G.add_weighted_edges_from([(item[0],item[1],float(item[2]))])
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

print(nx.average_shortest_path_length(G,weight='weight'))

myFile.close()
