#!/usr/bin/env python3
#User must specify clique size (k)
import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
    k = int(sys.argv[2])
    G=nx.MultiGraph()

else:
    print("Error: wrong number of arguments given")
    sys.exit()

lines = []
for edge in myFile:
    lines.append(tuple(edge.split()))

if(len(lines[0])==2):
    G.add_edges_from(lines)
elif(len(lines[0])>=3):
    for item in lines:
        G.add_weighted_edges_from([(item[0],item[1],float(item[2]))])
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

c=list(nx.k_clique_communities(G,k))

for item in c:
    for value in item:
        print(value, end=" ")
    print('')

myFile.close()
