#!/usr/bin/env python3
#Graph must be directed
#User must indicate which connected component they want based on the list given
#by the output of strongConnComps.py. Only single nodes with a self-loop will
#be considered strongly connected components by this function.

import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
    connComp = sys.argv[2]
else:
    print("Error: wrong number of arguments.")
    sys.exit()

lines = []
for edge in myFile:
    lines.append(tuple(edge.split()))
G = nx.MultiDiGraph()

if(len(lines[0])==2):
    G.add_edges_from(lines)
elif(len(lines[0])>=3):
    for item in lines:
        G.add_weighted_edges_from([(item[0],item[1],float(item[2]))])
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

myFile.close()

for item in nx.strongly_connected_component_subgraphs(G)[int(connComp)].edges():
    print(item[0],item[1])

