#!/usr/bin/env python3
#Graph must be connected if undirected, strongly connected if directed

import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
else:
    print("Error: wrong number of arguments.")
    sys.exit()

lines = []
for edge in myFile:
    lines.append(tuple(edge.split()))
if(sys.argv[2]=='u'):
    G = nx.Graph()
elif(sys.argv[2]=='d'):
    G=nx.DiGraph()
else:
    print("Error: graph type not correct. Use 'd' for directed graphs, 'u' for undirected graphs.")
    sys.exit()

if(len(lines[0])==2):
    G.add_edges_from(lines)
elif(len(lines[0])>=3):
    for item in lines:
        G.add_edge(item[0],item[1],weight=float(item[2]))
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

for item in nx.complement(G).edges():
    print(item[0], item[1])

myFile.close()
