#!/usr/bin/env python3
#User must specify whether the graph is directed or undirected

import networkx as nx
import sys

if(len(sys.argv)==3):
    myFile = open(sys.argv[1], 'r')
else:
    print("Error: wrong number of arguments.")
    sys.exit()

lines = []

for edge in myFile:
    lines.append(tuple(edge.split()))
if(sys.argv[2]=='d'):
    G = nx.DiGraph()
elif(sys.argv[2]=='u'):
    G = nx.Graph()
else:
    print("Error: type of graph incorrect. Use 'd' for directed, 'u' for undirected")

if(len(lines[0])==2):
    G.add_edges_from(lines)
elif(len(lines[0])>=3):
    for item in lines:
        G.add_weighted_edges_from([(item[0],item[1],float(item[2]))])
else:
    print("Error in input file. Wrong number of elements per line.")
    sys.exit()

myFile.close()

print(nx.transitivity(G))
