.TH NETX-INTERSECTIONARRAY 1 "24 July 2012"

.SH NAME

netx-intersectionArray


.SH SYNOPSIS

.B netx-intersectionArray
.I  inputFile

.SH GRAPH LIMITATIONS
\fBDirected:\fR No
.br
\fBUndirected:\fR Yes
.br
\fBSelf-Loops:\fR Yes
.br
\fBParallel Edges:\fR Yes
.br
\fBOther:\fR Graph must be distance-regular.
.br .br
.PP
.SH DESCRIPTION

\fBnetx-intersectionArray\fR prints the intersection array of the distance-regular graph. This function uses a software package called NetworkX that must be installed for the function to work. See \fBnetworkx.lanl.gov/reference/generated/networx.algorithms.distance_regular.intersection_array.html\fR for more information.
.br .P
.br .P
.PP
Example Output:					
.br .P						
([3,2], [1,3])
.br .P
.br .P
.PP
\fBinputFile\fR is a file in edge-list format that contains only text. It does not have any header information. The nodes can have any name, as long as each node has a unique name (i.e. you can't have two nodes both named "sam" in the same graph). Optionally, after listing the two nodes, various other edge attributes can be assigned. In this function, the first value is assumed to be the weight of the edge. No other attribute is used in this function. Below are two example input files. The first has no attributes, the second does.
.br .P
.PP
Example One:
.br .P
node1 node2 
.br .P
node3 node1
.br .P
node4 node5
.br .P
.br .P
.PP
Where there is an edge between the two nodes on the same line.
.br .P
.br .P
.PP
Example Two:
.br .P
node1 node2 4
.br .P
node3 node1 3.14
.br .P
node4 node5 2
.br .P
.br .P
.PP
Where there is an edge between the first two entries (nodes) on the same line and the third number is the weight of that edge.
.br .P
.br .P
.PP
.SH AUTHOR

Zachary Keller

.PP
July 2012

.PP 
High Performance Computing & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/hpcvg/
