#!/usr/bin/env python3
import networkx as nx
import sys

G=nx.MultiGraph()
if(len(sys.argv)==3):
    myFile=open(sys.argv[1], 'r')
    nodeFile=open(sys.argv[2], 'r')
    fileName = sys.argv[1]+".attributes.txt"
    f1=open(fileName, 'w')
else:
    print("Error: wrong number of arguments given")
    sys.exit()

lines = []

for edge in myFile:
    lines.append(tuple(edge.split()))

for x in range(len(lines)):
    G.add_edge(lines[x][0], lines[x][1])

myFile.close()

nodes = []
nodeDict = {}
for edge in nodeFile:
    nodes.append(tuple(edge.split()))

for item in nodes:
    nodeDict[item[0]]=item[1]

nodeFile.close()

deg = nx.degree(G)

sorted_list=[x for x in deg.items()]
sorted_list.sort(key=lambda x: x[0])

for item in sorted_list:
    f1.write(item[0])
    f1.write(" ")
    f1.write(str(item[1]))
    f1.write(" ")
    f1.write(nodeDict[item[0]])
    f1.write("\n")
f1.close()
