.TH IRIS-NODE 7 "Dec 2013" "NIST/ACMD" "HPCVG HEV"

.SH NAME
iris-node
- Simple Javascript interface and bindings to IRIS.

.SH DESCRIPTION

.BR iris-node
is a Node.js module that offers a simple Javascript interface and bindings to
the IRIS Control FIFO. It currently consists of two utilities for controlling
IRIS:
.IP
-
.BR iris-console (1)
a terminal console, and
.br
-
.BR iris-server (1)
a web server.

.SH AUTHOR
Wesley Griffin <wesley.griffin@nist.gov>

.SH SEE ALSO
.BR iris-console (1)
.BR iris-server (1)

