.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-sphereFBappBuilder 1 "September 2016" "NIST/ACMD/HPCVG" "HEV"
.SH NAME hev-sphereFBappBuilder	spellppBuilder
- Sphere FlipBook App Builder


.SH SYNOPSIS
.B  hev-sphereFBappBuilder pointsfile1 pointsfile2 ...

.SH DESCRIPTION
.PP
.I hev-sphereFBappBuilder
builds a flip book style application demo from a series of point files.

.SH AUTHOR
Steven G. Satterfield, steve@nist.gov, adapted the code to the HEV environment.
