.\" This is a comment
.TH qvd-utilities 3 "January 2013" "NIST/ACMD/HPCVG" "HEV"
.SH NAME
qvd-utilities - 
qvisdat utilities

.SH DESCRIPTION
.PP
.I
qvd-utilities 
is a collection of commands related to the visualization of
output from the QDPD program in collaboration with Nick Martys, EL.
See:
http://snippet.cam.nist.gov:8000/rave/wiki/SuspensionFlowVisProject

.PP
For details of the individual commands, refer to their respective on-line
manual page.

.PP
For other commands useful for this project but not directly included
in the family, refer to the \fISEE ALSO\fR section below.

.SH COMMANDS

.\"qvd-displayLUT - display Look Up Table
.\".br
qvd-extractFrames - extract qvisdat frames
.br
.\"qvd-extractAV - extract angular velocity from qvisdat file
.\".br
.\"qvd-flipBook - flip book
.\".br
.\"qvd-flipBookSGE - flip book sge
.\".br

qvd-frameList - create a frame list number sequence
.br
.\"qvd-optimizeLinesSGE - optimize the lines sge produced by qvd-toSGE
.\".br
.\"qvd-stressHistogram - stress histogram
.\".br
.\"qvd-toSGE - qvisdat to sge animation file
.\".br

qvd-rheometerAppBuilder - Rheometer Application Builder

qvd-shearingRocksAppBuilder - Shearing Rocks Application Builder

qvd-toIRIS - qvisdat to \fB.iris\fR file animation

qvd-toTIM - qvisdat to \fBhev-tim\fR files 

qvd-wireBox - wire frame box


.SH SEE ALSO
\fI
irisfly(1),
hev-tim(1)
\fR


.SH AUTHOR

.PP
Steven G. Satterfield, steve@nist.gov,  NIST/ITL/ACMD/HPCVG

\"  LocalWords:  qvd NIST HEV qvisdat QDPD Martys BFRL fISEE fR displayLUT br
\"  LocalWords:  extractFrames extractAV flipBook flipBookSGE sge frameList fB
\"  LocalWords:  optimizeLinesSGE toSGE stressHistogram rheometerAppBuilder tim
\"  LocalWords:  Rheometer shearingRocksAppBuilder toIRIS toTIM fBhev wireBox
\"  LocalWords:  fI irisfly hev
