#! /usr/bin/perl

# steve@nist.gov
$version="20080401";

use Getopt::Long;

sub usage {

print STDERR <<EOF

Usage: qvd-extractFrames [--[no]renumber]  frameList  < in.qvisdat > out.qvisdat

       where:
              frameList is a comma separated sequence of frames.
              The elements of the list must be increasing in order.
              An element can also be a range indicated by a dash.
	      For example:

                            1,2,4,5,10-20,35,80-100


	      --renumber indicates that the frame numbers will be renumbered
                         sequentially from 1.

              --norenumber indicates that the frame numbers will remain unchanged.
                           This is the default.


Version: $version
EOF
;

exit(1);

}

$renumber=0;

GetOptions("renumber!"    => \$renumber);

usage() if (@ARGV != 1);


$frameList=shift;
#print "frameList= $frameList\n";

@elements = split(/,/,$frameList);
$n=@elements;
$n=0;
foreach $elements(@elements) {
    @t=split(/-/,$elements);
    $m=@t;
    if ($m == 1) {
	$startFrm[$n]=$t[0];
	$stopFrm[$n]=$t[0];
    } else {
	$startFrm[$n]=$t[0];
	$stopFrm[$n]=$t[1];
    }

    $n++;
}
$lastFrame=$stopFrm[$n-1];

#for ($i=0; $i<$n; $i++) {
#	print "$startFrm[$i] to $stopFrm[$i]\n";
#}

$newFrameNumber=1;

$flag=1;
while (<STDIN>) {
    chop($_);
    if (/^frame\s+(\d+)/) {
	$flag=0;
	for ($i=0; $i<$n; $i++) {
	    if (($startFrm[$i]<=$1)&&($1<=$stopFrm[$i])) {
		$flag=1;
	    }
	}
	if ($flag) {
	    if ($renumber) {
		print "frame $newFrameNumber\n";
	    } else {
		print $_,"\n";
	    }
	    $newFrameNumber++;
	}
    } else {
	if ($flag) {
	    print $_,"\n";
	}
    }
    if ($1 > $lastFrame) {
        #print STDERR "$1 $lastFrame exit early\n";
        exit(0);
    }

}
exit(0);
