#! /bin/sh

case $# in
1)
	N=$1
	;;
*)
	N=1
	;;
esac

cat vecField.dat | awk -v n=$N '
{
    s=20;
    if (i++ == n) {
        i=0;
        print "ivarrow | ivposition", $1,$2,$3,$1+s*$4,$2+s*$5,$3+s*$6;

    }
}'

