#!/bin/sh
file=$IRISFLY_HIDE_SHOW_WINDOWS

if [ -z "$file" ]
then dtk-msgError "irisfly-showWindows: no window file" 1>&2
    exit 1
fi

if [ ! -w "$file" ]
then dtk-msgError "irisfly-showWindows: no writeable window file" 1>&2
    exit 1
fi

while read window
do dtk-msgDebug "irisfly-showWindows: raising window \"$window\"" 1>&2
    hev-showWindow $window
done < $file
