// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef hev_xyzPositioner_h
#define hev_xyzPositioner_h
#include <FL/Fl.H>
#include "hev-xyzPositionerGlobals.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Input.H>
#endif
