#!gmake

PUBLIC_BINS = hev-navigationControl

MAN_PAGES = *.1

include $(HEV_IDEA_DIR)/gnumakefile.include

# add this to tie chnges in the fluid file to the main program
hev-navigationControl.d: hev-navigationControl.cxx


