# Bare bones GNUmakefile
# This directory is a bit outside the normal HEV framework,
# so its not clear if the usual HEV GNUmakefile works here.
# -sgs


build:
	echo in compare-binary
	echo ; \
	echo ; \
	echo "# --------------------------------" ; \
	echo ; \
	echo compare-binary ; \



install: build
	@if [ ! -d  ${HEVROOT}/test/renderTest/bin ] ; then mkdir ${HEVROOT}/test/renderTest/bin ; fi
	cp compare-binary ${HEVROOT}/test/renderTest/bin


clean:

distclean:

