.TH hev-eulerToVector 1 "May 2009"
.SH NAME

hev-eulerToVector

.SH SYNOPSIS

\fBhev-eulerToVector [-c N]

.SH DESCRIPTION

\fBhev-eulerToVector\fR converts lines from stdin containing an Euler angle
rotations to lines on stdout containing the eqivalent xyz vector rotation.

.SH OPTIONS

.IP "\fB-c \fIN\fR"
Skip the first \fIN\fR tokens on each line before evaluating the next three
tokens as h, p and r Euler angles.
.SH AUTHOR

.PP
John Kelso <kelso@nist.gov>, Steve Satterfield <steve@nist.gov>
.br
.br
\fBhttp://www.nist.gov/acmd/hpcvg/\fR

