.TH IRIS-WEBUI 1 "Jul 2015" "NIST/ACMD" "HPCVG / HEV"

.SH NAME
iris-webui
- web-based user interface to irisfly

.SH DESCRIPTION

\fBiris-webui\fR is an MCP file that launches a web-based user interface to \fBirisfly\fR(1).

.SH EXAMPLE

irisfly --ex cow.osg webui.mcp

.SH BUGS

The Scenegraph visualization likely doesn't work. It has only been tested on a single scene.

.SH AUTHOR
Wesley Griffin

.SH SEE ALSO
.BR iris (1),
.BR iris-fly (1),
.BR iris-viewer (1),
.BR hev-masterControlPanel (1).
