.TH hev-wiggleNav 1 "April, 2012" "NIST/MCSD" "MCSD HEV"
.SH NAME

hev-wiggleNav

.SH SYNOPSIS

\fBhev-wiggleNav\fR [ --noescape ]

.SH PARAMETERS

.IP noescape
if supplied, specifies that the GUI can't be killed by pressing the window
manager's close button, or by pressing escape in the GUI window.

.SH DESCRIPTION

\fBhev-wiggleNav\fR is a GUI which causes the virtual environment to rock
back and forth, providing enhanced depth cues in desktop windows by means of
motion parallax.

\fBhev-wiggleNav\fR can be started by pressing the "wiggle" button in the
"idea" button when running in a desktop environment.

.SH AUTHOR

.PP
John Kelso <kelso@nist.gov>
.br
NIST High Performance Computing and Visualization Group
.br
April 2012
.br
\fBhttp://www.nist.gov/mcsd/hpcvg/\fR
