.TH SAVG\-CLOCK 1 "26 May 2009"
.SH NAME
savg-clock \- SAVG ToolBox: clock
.SH SYNOPSIS
.B savg-clock
.SH DESCRIPTION
.I savg-clock
creates a unit sized object in the shape of a clock
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-clock
.SH EXAMPLES
.TP
.B savg-clock | savg-scale 2 2 2 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







