.TH SAVG\-OBJECT 1 "26 May 2009"
.SH NAME
savg-object \- SAVG ToolBox: object
.SH SYNOPSIS
.B savg-object
.SH DESCRIPTION
.I savg-object  phone/screen/box/flashlight/light
creates a unit sized object in one of 5 possible shapes
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-object phone/screen/box/flashlight/light
.SH EXAMPLES
.TP
.B savg-object phone | savg-scale 2 2 2 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







