.TH SAVG\-RMCOM 1 "26 May 2009"
.SH NAME
savg-rmcom \- SAVG ToolBox: rmcom
.SH SYNOPSIS
.B savg-rmcom
.SH DESCRIPTION
.I savg-rmcom [file.savg]
removes the comment lines in \fIsavg\fP files (\fISAVG ToolBox\fP).  It 
accepts input from
.I stdin
and outputs to
.I stdout.
If invalid arguments or no arguments are given, 
then 
.I savg-rmcom
prints usage information and terminates.
.SH OPTIONS
.TP
.B \  file.savg
savg file for input
.SH EXAMPLES
.TP
.B savg-rmcom file.savg > file2.savg
Reads from 
.I file.savg
and  outputs to 
.I file2.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







