.TH savg-plus3d  1 "September 2009" "NIST/MCSD/SAVG" 
.SH NAME
savg-plus3d
.SH SYNOPSIS
.B savg-plus3d

.SH DESCRIPTION
.I savg-plus3d

Creates a 3-dimensional plus sign glyph.  This is often used to mark the
location of a pointer.  It simply uses savg-cone to create six cones, with
an extent of -1 to 1 in each direction.

.SH SEE ALSO
savg-cone
