.TH SAVG\-XYZPLANES 1 "16 February 2005"

.SH NAME
savg-xyzPlanes \- SAVG Toolbox: xyzPlanes
.SH SYNOPSIS
.B savg-xyzPlanes
[-n value]

.SH DESCRIPTION
.I Savg-line-arrow
Generates 3 planes, at x=0,y=0,z=0, all centered at the origin, and
all 2 units wide and high to stdout.
.SH EXAMPLES
.TP
.B "savg-xyzPlanes | savg-color -b 1 > blue-planes.savg"
Creates 3 planes, colors them blue, and puts them in the SAVG format file blue-planes.savg.
.PP
.SH AUTHOR
.PP
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
February 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/
