.TH SAVG\-SQUARE 1 "30 April 2010"
.UC 4
.SH NAME
savg-square \- SAVG Toolbox: regular polygon
.SH SYNOPSIS
.B savg-square
[val]
.PP
.br
.SH DESCRIPTION
.I Savg-square
generates a square centered at (0,0). 
.SH OPTIONS
.PP
.SH EXAMPLES
.TP
.B "savg-square > square.savg"
Creates a square and puts it in the SAVG format file 
.I square.savg.

.PP
.SH AUTHOR
.PP
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
April, 2010
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







