.TH SAVG\-LIGHTING 1 "26 May 2009"
.SH NAME
savg-lighting \- SAVG ToolBox: lighting
.SH SYNOPSIS
.B savg-lighting on/off/auto/default
.SH DESCRIPTION
.I savg-lighting
specifies the lighting mode for \fIsavg\fP files (\fISAVG ToolBox\fP).  It 
accepts input from
.I stdin
and outputs to
.I stdout.
If invalid arguments or no arguments are given, 
then 
.I savg-lighting
prints usage information and terminates.
.SH OPTIONS
.TP
.B \   savg-lighting on/off/auto//default
.SH EXAMPLES
.TP
.B savg-lighting off < in.savg > out.savg
Reads from 
.I in.savg
and sets the lighting to off.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







