.TH SAVG\-CHAIR 1 "26 May 2009"
.SH NAME
savg-chair \- SAVG ToolBox: chair
.SH SYNOPSIS
.B savg-chair
.SH DESCRIPTION
.I savg-chair
creates a unit sized object in the shape of a chair
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-chair
.SH EXAMPLES
.TP
.B savg-chair | savg-scale 2 2 2 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







