.TH SAVG\-DIFFUSE 1 "26 May 2009"
.SH NAME
savg-diffuse \- SAVG ToolBox: diffuse
.SH SYNOPSIS
.B savg-diffuse r g b/default
.SH DESCRIPTION
.I savg-diffuse
sets the diffuse color for \fIsavg\fP files (\fISAVG ToolBox\fP).  It 
accepts input from
.I stdin
and outputs to
.I stdout.
If invalid arguments or no arguments are given, 
then 
.I savg-diffuse
prints usage information and terminates.
.SH OPTIONS
.TP
.B \   savg-diffuse val val val or savg-diffuse default
Accepts floating 
point numbers from 0 to 1 and defaults to 1.
.SH EXAMPLES
.TP
.B savg-diffuse 0.5 0.2 0.1 < in.savg > out.savg
Reads from 
.I in.savg
and set the diffuse to 0.5,0.2,0.1.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







