.TH SAVG\-TEXT 1 "26 January 2005"

.SH NAME
savg-text \- SAVG Toolbox: text
.SH SYNOPSIS
.B savg-text
[string]

.SH DESCRIPTION
.I Savg-text
generates text containing the requested string.
.SH OPTIONS
(none)
.SH EXAMPLES
.TP
.B "savg-text 'Hello' > Hello.savg"
Creates text and puts it in the SAVG format file text.savg.


.PP
.SH AUTHOR
.PP
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
June 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/
