.TH SAVG\-RGB2HSI 1 " April 2007"
.SH NAME
savg-rgb2hsi \- SAVG ToolBox: rgb2hsi
.SH SYNOPSIS
.B savg-rgb2hsi
.SH DESCRIPTION
.I Savg-rgb2hsi
replaces the rgb values of \fIsavg\fP files (\fISAVG ToolBox\fP) with the
corresponding hsi values.  It 
accepts input from
.I stdin
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \  savg-rgb2hsi
.SH EXAMPLES
.TP
.B savg-rgb2hsi < in.savg > out.savg
Reads from 
.I in.savg
and sets the rgb values to hsi values, leaving the alpha value unchanged.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
April 2007
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







