.TH SAVG\-COMPUTER 1 "26 May 2009"
.SH NAME
savg-computer \- SAVG ToolBox: computer
.SH SYNOPSIS
.B savg-computer
.SH DESCRIPTION
.I savg-computer
creates a unit sized object in the shape of a computer
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-computer
.SH EXAMPLES
.TP
.B savg-computer | savg-scale 2 2 2 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







