.TH SAVG\-CUBE 1 "26 January 2005"

.SH NAME
savg-cube \- SAVG Toolbox: cube
.SH SYNOPSIS
.B savg-cube
[no arguments]

.SH DESCRIPTION
.I Savg-cube
generates a cube centered at the origin and 1 unit in each direction to stdout with one corner located at (-1,-1,-1) and the corner farthest from it located at (1, 1, 1).
.SH OPTIONS
(none)
.SH EXAMPLES
.TP
.B "savg-cube > cube.savg"
Creates a cube and puts it in the SAVG format file cube.savg.
.SH SEE ALSO
savg-cone, savg-cylinder, savg-tetra, savg-octa, savg-sphere, savg-regpoly
.PP
.SH AUTHOR
.PP
Brandon M. Smith
.TP
SAVG Toolbox Project
Version 1.0
.br
Summer 2004
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/
