.TH SAVG\-RGB2HSV 1 " April 2007"
.SH NAME
savg-rgb2hsv \- SAVG ToolBox: rgb2hsv
.SH SYNOPSIS
.B savg-rgb2hsv
.SH DESCRIPTION
.I Savg-rgb2hsv
replaces the rgb values of \fIsavg\fP files (\fISAVG ToolBox\fP) with the
corresponding hsv values.  It 
accepts input from
.I stdin
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \  savg-rgb2hsv
.SH EXAMPLES
.TP
.B savg-rgb2hsv < in.savg > out.savg
Reads from 
.I in.savg
and sets the rgb values to hsv values, leaving the alpha value unchanged.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
April 2007
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







