.TH SAVG\-LINE 1 "26 May 2009"
.SH NAME
savg-line \- SAVG ToolBox: line
.SH SYNOPSIS
.B savg-line
.SH DESCRIPTION
.I savg-line
creates a unit line in the x direction
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-line
.SH EXAMPLES
.TP
.B savg-line | savg-scale 2 1 1 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







