.TH savg\-add-normals 1 "January 2009"
.SH NAME
savg-add-normals 
.SH SYNOPSIS
.B savg-add-normals 
[-replace]

.SH DESCRIPTION
.I savg-add-normals
adds normal vectors to polygons. 
It calculates normals for polygon vertices that do not already
have normals, and it will optionally replace existing normals.

It reads geometry data in .savg format on stdin, and writes output in .savg
format to stdout.

.SH OPTIONS
.TP
.B -replace
Replace existing normal data on polygon vertices.


.SH EXAMPLES
.TP
.B savg-add-normals < lacking.savg > replete.savg
Provides normals for polygon vertices that do not have normals in lacking.savg.

.TP
.B savg-sphere | savg-add-normals -replace > facetSphere.savg
Replaces the normals provided by savg-sphere to produce a facetted sphere.


.SH SEE ALSO
savg-rm-normals, savg-output-normals







