.TH SAVG\-LINE-ARROW 1 "29 December 2004"

.SH NAME
savg-line-arrow \- SAVG Toolbox: line-arrow
.SH SYNOPSIS
.B savg-line-arrow
[-n value]

.SH DESCRIPTION
.I Savg-line-arrow
generates a unit-sized arrow (1 unit tall, base with radius of .2 unit) to stdout.
.SH EXAMPLES
.TP
.B "savg-line-arrow > arrow.savg"
Creates an arrow and puts it in the SAVG format file arrow.savg.
.PP
.SH AUTHOR
.PP
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
December 2004
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/
