.TH SAVG\-ARROW 1 "27 December 2004"

.SH NAME
savg-arrow \- SAVG Toolbox: arrow
.SH SYNOPSIS
.B savg-arrow
[value]

.SH DESCRIPTION
.I savg-arrow
generates a unit-sized arrow (1 unit tall, base with radius of .2 unit) to stdout.
Usage messages are produced when options are incorrectly specified.
.SH OPTIONS
.PP
.TP
.B value
Specify the number of points around the base of the stem or head. (default 5).
.SH EXAMPLES
.TP
.B "savg-arrow 10 > arrow.savg"
Creates an arrow with 10 polygons around and puts it in the SAVG format file arrow.savg.
.PP
.SH AUTHOR
.PP
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
December 2004, Modified June 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/
