.TH SAVG\-HSV2RGB 1 " April 2007"
.SH NAME
savg-hsv2rgb \- SAVG ToolBox: hsv2rgb
.SH SYNOPSIS
.B savg-hsv2rgb
.SH DESCRIPTION
.I Savg-hsv2rgb
replaces the hsv values of \fIsavg\fP files (\fISAVG ToolBox\fP) with the
corresponding rgb values.  It 
accepts input from
.I stdin
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \  savg-hsv2rgb
.SH EXAMPLES
.TP
.B savg-hsv2rgb < in.savg > out.savg
Reads from 
.I in.savg
and sets the hsv values to rgb values, leaving the alpha value unchanged.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
April 2007
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







