.TH SAVG\-HSI2RGB 1 " April 2007"
.SH NAME
savg-hsi2rgb \- SAVG ToolBox: hsi2rgb
.SH SYNOPSIS
.B savg-hsi2rgb
.SH DESCRIPTION
.I Savg-hsi2rgb
replaces the hsi values of \fIsavg\fP files (\fISAVG ToolBox\fP) with the
corresponding rgb values.  It 
accepts input from
.I stdin
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \  savg-hsi2rgb
.SH EXAMPLES
.TP
.B savg-hsi2rgb < in.savg > out.savg
Reads from 
.I in.savg
and sets the hsi values to rgb values, leaving the alpha value unchanged.  Then outputs to 
.I out.savg.
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
April 2007
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







