.TH SAVG\-FLAG 1 "26 May 2009"
.SH NAME
savg-flag \- SAVG ToolBox: flag
.SH SYNOPSIS
.B savg-flag
.SH DESCRIPTION
.I savg-flag
creates a unit sized object in the shape of a flag
and outputs to
.I stdout.
.SH OPTIONS
.TP
.B \   savg-flag
.SH EXAMPLES
.TP
.B savg-flag | savg-scale 2 2 2 > out.savg
.SH BUGS
(none)
.SH AUTHOR
Adele Peskin
.TP
SAVG Toolbox Project
Version 1.0
.br
March 2005
.PP 
Scientific Applications & Visualization Group
.br
NIST
.br
.B www.nist.gov/mcsd/savg/







