FUNC RgbaLut1D simple
  COLOR_INTERP CIE
  PRE_INTEGRATE false
  LOOKUP_INTERP LINEAR
  TABLE_TYPE FLOAT
  TABLE_LEN 256
  COMBINE_RGBA true
  NORMALIZE true
  LIGHTING GRAD_OPAQUE
  RGBLUT
        -1000 1 0 0
        1312 0 0 1
  END_RGBLUT
  ALPHALUT
        -1000 0.01
        1312 0.01
  END_ALPHALUT
END_FUNC simple


