#!gmake

PUBLIC_BINS = hev-desktopWand

MAN_PAGES = hev-desktopWand.1

include $(HEV_IDEA_DIR)/gnumakefile.include

# add this to tie changes in the fluid file to the main program
hev-desktopWand.d: hev-desktopWandGUI.cxx

