.\" This is a comment
.\" The extra parameters on .TH show up in the headers
.TH hev-blankwalls 1 "May 2011" "NIST/ACMD/HPCVG" "HEV"

.SH NAME

hev-blankwalls - convenience utility to run blank 3 RAVE screens

.SH SYNOPSIS

\fBhev-blankwalls\fR 

.SH DESCRIPTION

\fBhev-blankwalls\fR is a convenience utility to 
blank, i.e. display only black, on the 3
RAVE screens.

This command is specific to the RAVE.  Its intended purpose is to blank the
user desktop during the portion of RAVE demos where a a browser is used on the
front wall for a power point style presentation.



.SH AUTHOR

.PP
Steve Satterfield, steve@nist.gov
.br
http://www.nist.gov/itl/math/hpcvg


