.TH HEV-MESHSTATS 1 "December 2014" "NIST/ACMD" "HPCVG HEV"

.SH NAME
hev-meshStats
- Print OpenSceneGraph statistics about files

.SH SYNOPSIS
.B hev-meshStats
.RI [ file
.IR .\|.\|.\| ]

.SH DESCRIPTION
.B hev-meshStats
prints OpenSceneGraph statistics about files.

.SH AUTHOR
Wesley Griffin, wesley.griffin@nist.gov

