.TH hev-textInput 1 "August 14, 2012"
.SH NAME

hev-textInput

.SH SYNOPSIS

\fBhev-textInput [ text ]

.SH DESCRIPTION

\fBhev-textInput\fR displays a window that allows text input.  Whenever the
Enter key is pressed, the contents of the window is written to standard
output.

.SH OPTIONS

.IP \fItext\fR
specifies the initial text string to be displayed.  If omitted, no text is
initially displayed.

.SH AUTHOR

.PP
John Kelso <kelso@nist.gov>
.br
NIST
.br
\fBhttp://www.nist.gov/acmd/hpcvg/\fR

