#!gmake

# see $HEVROOT/idea/GNUmakefile.template for an explanation of what these
# defintions do


PUBLIC_BINS = showCursorPositionInImage

include $(HEV_IDEA_DIR)/gnumakefile.include

showCursorPositionInImage.d: showCursorPositionInImageGUI.cxx
