// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef showCursorPositionInImageGUI_h
#define showCursorPositionInImageGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *imageButton;
Fl_Double_Window* make_main_window();
extern Fl_Double_Window *sub_window;
#include <FL/Fl_Box.H>
extern Fl_Box *image_box;
Fl_Double_Window* make_sub_window();
#endif
