.TH iris-getName 1 "May 2012"

.SH NAME
iris-getName

.SH SYNOPSIS 
.B iris-getName
file

.SH DESCRIPTION

\fBiris-getName\fR prints the name of the root node returned by loading an OSG
loadable file.

.SH EXAMPLE

iris-getName tape.osg

.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST High Performance Computing and Visualization Group
.br
May 2012
.br
\fBhttp://www.nist.gov/mcsd/hpcvg/\fR
 
