.TH iris-bounds 1 "February 2011"

.SH NAME
iris-bounds

.SH SYNOPSIS 
.B iris-bounds
--help --sphere --box file [ ... ]

.SH DESCRIPTION

\fBiris-bounds\fR prints the bounding sphere and bounding box of a list of IRIS loadable files

.SH OPTIONS

.TP
--help
.br
Print the usage message and exit

.TP
--sphere
.br
Print only the bounding sphere

.TP
--box
.br
Print only the bounding box

.P
By default both the bounding sphere and bounding box are printed.

.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST High Performance Computing and Visualization Group
.br
February 2011
.br
\fBhttp://www.nist.gov/mcsd/hpcvg/\fR
 
