.TH iris-immersivePaneBorders 1 "February 2011"

.SH NAME
iris-immersivePaneBorders

.SH SYNOPSIS 

.B iris-immersivePaneBorders [ file ... ]

.SH OPTIONS

.TP 
file
.br
the name of one or more files to be loaded

.SH DESCRIPTION

\fBiris-immersivePaneBorders\fR prints the control commands to create white
outlines around the iris::ImmersivePane objects loaded on the command line
or the IRIS_FILES environment variable. This can hopefully help desktop
developers see how their models will fit into an immersive environment.

.SH AUTHOR

.PP
John Kelso, kelso@nist.gov
.br
NIST High Performance Computing and Visualization Group
.br
February 2011
.br
\fBhttp://www.nist.gov/mcsd/hpcvg/\fR
 
